# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant
#
# This is the general, non-filtered java build using ant that will run with github actions

name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          check-latest: true
      - uses: actions/checkout@v3
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml clean test